Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=25, manual_split=False, model='vgg11', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg11) till index 25
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Read 254.37291526794434 MBs for this batch
Streaming imagenet data took 14.646423101425171 seconds

Epoch: 0
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Memory occpied: (1618.0, 3.0)
Time of next(dataloader) is: 7.535260200500488
Time for copying to cuda: 0.37671613693237305
Memory occpied: (2768.0, 106.0)
Memory occpied: (2768.0, 390.0)
Memory occpied: (2768.0, 708.0)
Memory occpied: (2768.0, 1026.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 49, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/usr/local/lib/python3.8/dist-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 719, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 2.99 GiB (GPU 0; 14.76 GiB total capacity; 13.58 GiB already allocated; 73.75 MiB free; 13.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (15036.0, 14464.0)
Read 246.17637538909912 MBs for this batch
Streaming imagenet data took 16.49425983428955 seconds
