Namespace(all_in_cos=False, batch_size=2000, cached=True, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=36, model='vgg19', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, transformed=True, use_intermediate=False)
Nb GPUS  2
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg19) till index 36
The mode is:  vanilla
Start 0, end 2000, post_step 1000

Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Decompress data took 0.1082763671875 seconds
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Total decompress data took 2.8323371410369873 seconds
Decompress data took 0.10430717468261719 seconds
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Memory occpied: (1822.0, 3.0)
Total decompress data took 2.836491346359253 seconds
Read 308.89431381225586 MBs for this batch
Streaming imagenet data took 10.391084909439087 seconds
The mode is:  vanilla
Start 2000, end 4000, post_step 1000


Epoch: 0
Memory occpied: (1822.0, 3.0)
Time of next(dataloader) is: 0.9423649311065674
Time for copying to cuda: 0.3053267002105713
Memory occpied: (2972.0, 790.0)
Memory occpied: (2972.0, 1222.0)
Decompress data took 0.10123944282531738 seconds
Memory occpied: (2972.0, 1676.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 66, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 11.96 GiB (GPU 0; 14.76 GiB total capacity; 1.66 GiB already allocated; 11.85 GiB free; 1.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (2972.0, 14646.0)
Total decompress data took 2.9091572761535645 seconds
Decompress data took 0.10622596740722656 seconds
The whole process took 23.49147343635559 seconds
Total decompress data took 2.6111879348754883 seconds
Read 306.5873851776123 MBs for this batch
Streaming imagenet data took 8.937477827072144 seconds
