Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=25, model='vgg11', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg11) till index 25
The mode is:  vanilla
Start 0, end 2000, post_step 1000

Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Memory occpied: (1762.0, 3.0)
Read 308.89431381225586 MBs for this batch
Streaming imagenet data took 9.055247783660889 seconds
The mode is:  vanilla
Start 2000, end 4000, post_step 1000


Epoch: 0
Time of next(dataloader) is: 0.9400813579559326
Time for copying to cuda: 0.29956626892089844
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 66, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 11.96 GiB (GPU 0; 14.76 GiB total capacity; 1.62 GiB already allocated; 11.91 GiB free; 1.62 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (1762.0, 14602.0)
The whole process took 21.563227891921997 seconds
Read 306.5873851776123 MBs for this batch
Streaming imagenet data took 9.151823997497559 seconds
