Namespace(batch_size=2000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=17, manual_split=False, model='alexnet', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (alexnet) till index 17
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Memory occpied: (8085.0, 3.0)
Read 254.37291526794434 MBs for this batch
Streaming imagenet data took 18.13306188583374 seconds

Epoch: 0
Time of next(dataloader) is: 11.13723373413086
Time for copying to cuda: 0.44463300704956055
Read 246.17637538909912 MBs for this batch
Streaming imagenet data took 23.5864155292511 seconds
Memory occpied: (8085.0, 3.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/alexnet.py", line 46, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/usr/local/lib/python3.8/dist-packages/torch/_jit_internal.py", line 422, in fn
    return if_false(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 719, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 356.00 MiB (GPU 0; 14.76 GiB total capacity; 2.24 GiB already allocated; 328.75 MiB free; 2.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

The whole process took 50.543846130371094 seconds
